first_dw:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: '1'
      port: 5432
      dbname: postgres
      schema: data_warehouse
      threads: 1